//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumToPhoto
    {
        public int AlbumToPhotoID { get; set; }
        public int AlbumID { get; set; }
        public int PhotoID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
