//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotoLibraryEntities : DbContext
    {
        public PhotoLibraryEntities()
            : base("name=PhotoLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<AlbumToPhoto> AlbumToPhotoes { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<LikePhoto> LikePhotoes { get; set; }
        public virtual DbSet<LogMessage> LogMessages { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
